spring.application.name=rag-ai-test

spring.datasource.url=jdbc:h2:file:~/spring-boot-h2-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Enable the H2 web console for easy access
spring.h2.console.enabled=true

# Customize the H2 console access path (optional, default is /h2-console)
spring.h2.console.path=/h2-console

# Hiberna DDL-Auto (optional, for schema management)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true